DELIMITER $$

CREATE TRIGGER sales_bi_trg 
    BEFORE INSERT ON sales 
    FOR EACH ROW
BEGIN 
DECLARE row_count INTEGER;

    SELECT COUNT(*) 
    INTO row_count 
    FROM customer_sales_total
    WHERE CUSTOMER_ID=NEW.CUSTOMER_ID;

IF row_count > 0 THEN 
UPDATE customer_sales_total
    SET SALE_VALUE=SALE_VALUE+NEW.SALE_VALUE 
    WHERE CUSTOMER_ID=NEW.CUSTOMER_ID;
ELSE 
    INSERT INTO customer_sales_total
        (CUSTOMER_ID,SALE_VALUE) 
    VALUES(NEW.CUSTOMER_ID,NEW.SALE_VALUE);
END IF;

END$$

CREATE TRIGGER sales_bu_trg
    BEFORE UPDATE ON sales
    FOR EACH ROW 
BEGIN
    UPDATE customer_sales_total
    SET SALE_VALUE=SALE_VALUE+(NEW.SALE_VALUE-OLD.SALE_VALUE)
    WHERE CUSTOMER_ID=NEW.CUSTOMER_ID;
END$$

CREATE TRIGGER sales_bd_trg 
    BEFORE DELETE ON sales 
    FOR EACH ROW
BEGIN

UPDATE customer_sales_total
    SET SALE_VALUE=SALE_VALUE-OLD.SALE_VALUE
WHERE CUSTOMER_ID=OLD.CUSTOMER_ID; 

END$$

